cmd/provision/provision.go
also improved the stderr output when retrying
close #22
=> changed the retry timeout to 180 seconds

go.mod, go.sum
To point to the latest -envoy and -golib repo.
=> updated deps

apigee/app.go, apigee/edge_client.go, cmd/bindings/bindings.go, cmd/bindings/bindings_test.go, cmd/provision/provision.go, cmd/samples/samples.go, cmd/samples/samples_test.go, shared/shared.go
Fix #47 that was supposed to be done in #44...
Modified the URL query in fetching OAuth token such that credentials with special characters should work now.
Modified some output messages.
Changed the apigee.Application to address json decoding error.
=> supporting MFA and fixed some misc issues

cmd/token/token.go, shared/shared.go
=> changed all descriptions of flags to start with lowercase

cmd/bindings/bindings.go
=> output error

apigee/cache_test.go, apigee/edge_client.go, apigee/edge_client_test.go, apigee/kvm_test.go, apigee/proxies_service.go, apigee/proxies_service_test.go, apigee/revision_test.go, apigee/timestamp_test.go, cmd/provision/provision.go, shared/jwks.go, shared/jwks_test.go, shared/shared.go, shared/shared_test.go
Fix #50 
Removed commented code in proxy_services.go
=> Unit tests in all packages

apigee/proxies_service_test.go, go.mod, go.sum
=> prerelease for 1.2.0 and one more unit test

shared/shared.go
=> make internalProxyURL static

apigee/proxies_service.go, cmd/provision/proxy.go
=> added slash to forward slash replacement in zip files

cmd/bindings/bindings.go
=> deprecate bindings verify

cmd/provision/config.go, cmd/provision/provision.go, cmd/provision/provision_test.go, go.mod, go.sum
Also added tests on remote-service proxy verification failure.
=> Reusing existing propertyset for next-gen saas

cmd/provision/config.go, cmd/provision/config_test.go, cmd/provision/provision.go
=> reading analytics sa from given config.yaml

cmd/provision/config.go
=> remove env label from service account

cmd/samples/templates/istio-1.7/apigee-envoy-adapter.yaml, cmd/samples/templates/istio-1.9/apigee-envoy-adapter.yaml
Added the AnalyticsSecret condition back which was accidentally removed in #168.
=> fixed the templates

cmd/testdir/testfile, cmd/util_test.go
=> added unit test on CopyFromEmbedded

cmd/samples/templates/istio-1.7/envoyfilter-sidecar.yaml, cmd/samples/templates/istio-1.9/envoyfilter-sidecar.yaml
=> add proxyVersion guards

cmd/bindings/bindings.go, cmd/bindings/bindings_test.go, go.mod, go.sum
=> updated deps on -golib and -envoy; modified or replaced target

cmd/samples/templates/envoy-1.15/envoy-config.yaml, cmd/samples/templates/envoy-1.16/envoy-config.yaml
=> fix tls certs setting in envoy templates

cmd/samples/samples.go, cmd/samples/samples_test.go
=> add envoy 1.18 and istio 1.10; made istio 1.9 default

go.mod, go.sum, hcl_shim/go.mod, hcl_shim/hcl/printer/shim.go, hcl_shim/shim.go
=> remove dependency on hcl library

cmd/samples/samples.go
=> default adapter-host to 127.0.0.1

cmd/bindings/bindings_test.go, cmd/provision/config.go, cmd/provision/provision.go, cmd/provision/provision_test.go, cmd/provision/proxy.go, cmd/token/token.go, cmd/token/token_test.go, shared/shared.go, shared/shared_test.go
=> replace hybrid with Apigee X/Hybrid

cmd/samples/samples.go, cmd/samples/templates/envoy-1.15/envoy-config.yaml, cmd/samples/templates/envoy-1.16/envoy-config.yaml
=> support target port and tls in samples

cmd/samples/templates/istio-1.9/envoyfilter-sidecar.yaml
=> replace deprecated fields in EnvoyFilter CR

cmd/samples/templates/istio-1.9/envoyfilter-sidecar.yaml
=> Fix typo in Istio 1.6 template

.github/workflows/build.yaml
=> Update checkout action to v2

Dockerfile_releaser
=> Remove use of deprecated goreleaser.sh

.allstar/binary_artifacts.yaml
=> allstar should ignore apigee callouts

cmd/provision/proxies/remote-service-gcp/apiproxy/resources/py/get-runtime-version.py
=> more robust parsing of dpcolor to a semver
